#!/usr/bin/env bash

ssh ubuntu@100.25.144.23 -i ~/.ssh/school
mkdir -p ~/.ssh && touch ~/.ssh/authorized_keys
chmod 700 ~/.ssh && chmod 600 ~/.ssh/authorized_keys
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCxWgbSIpjq+7gWJ91rkFY5Xu9sXFGRmF7dgNkkMIwZa1+ZTMyFLPoJmTG+oDYuE8la8fhXCwY2Ge2qzpJR974uJxyFjC3qxduEBmBjF5crc7mHZj9E9yTzZeDXptYZQGkVe1BWscjrHFCCvONiQnuJSdkh2hVE6wCLOjo+rsprFOSSDijc/3oq4b089tLAzEt8Fc/GNMYlaRHEflSjygiVFhUqGqAhAXCZy0u2r+5MUpg3f1EFNOtVgzxCdMk+fg0Wc6sQK1xxL02PUbVpNGoGRGWn25RHsZJM1yS+4Zg1UOZx8mHdcRPuSFEYd2c7abu+LKOzBUhbx6/coQm6vKFKctduqHx5cfXlkc/Yw+tcmb5DIzSyOccnxN8O0iO/5m1X8pvGDDT95nJ0J6W8lPY3EL7ScMbtY4mRP7WvetfQENvqk1Vj0mEDRM/1EQTtG7tk1KDzGI7MZRLjxvC30VTAZSzstWlpOctVaKmmELZsbJ/HZySv7ZTN8DnYxbTa4kk= root@dd096abbc1e4
